#%RAML 1.0
---

# Validation:
# https://raml-org.github.io/playground/custom_validation.html

title: Nota API
baseUri: http://localhost:9000
version: v1
mediaType: application/json
types:
  UUID:
    type: string
    pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
  Token:
    type: object
    properties:
      token:
        required: true
        type: UUID
      timestamp:
        required: true
        type: number
  userPost:
    type: object
    properties:
      _id:
        type: number
      author_ID:
        type: string
      body:
        type: string
      tags:
        type: array
        items:
          type: string
      title:
        type: string
      img_URL:
        type: string
      date_created:
        type: number
      location:
        type: object
        properties:
          latitude:
            type: number
          longitude:
            type: number
      true_location:
        type: boolean
      access_key:
        type: string

/auth:
  post:
    description: "Creates an authorization token to be used for authorizing API calls."
    responses:
      200:
        body:
          application/json:
            type: Token
            example: |
              {
                "token": "6bf73119-ff54-40d6-bbd5-a2590b9eb66f",
                "timestamp": "1635366449733"
              }

/version:
  get:
    description: "Returns the version of the APP."
    responses:
      200:
        body:
          type: string
          example: "Service v0.0.0"
      401:
        body:
          type: string
          example: "No Authentication Token Provided"

/userpost:
  post:
    description: "Creates a new user post document and returns it."
    responses:
      201:
        body:
          application/json:
            type: userPost
      400:
        description: "A required field in the request is missing."
        body:
          type: string
          example: "UserPost validation failed: author: Path `author` is required."
      500:
        body:
          type: string
  /{id}:
    get: 
      description: "Returns the post with the matching id"
      responses:
        200:
          body:
            application/json:
              type: userPost
        404:
          body:
            type: string
            example: "User Not Found"
        500:
          body:
            type: string
    delete:
      description: "Deletes a user post."
      responses:
        200:
        404:
          body:
            type: string
            example: "User Post Not Found"
        500:
          body:
            type: string
    patch:
      description: "Update a userpost with data provided in an update field in req.body"
      body:
        application/json:
          example: { "update" : { "title": "exampleUpdate", "body": "exampleUpdate"}}
      responses:
        200:
          body:
            application/json:            
              type: userPost
        404:
          body:
            type: string
            example: "User Post Not Found"
        500:
          body:
            type: string

/userPosts:
  post:
    description: Returns an array of Userposts which matches the filters provided in req.body.
    body:
      application/json:
        example: { "title" : "Post Title", "tags" : ["Tag1", "Tag2"] }, "page": "1" }
    responses:
      200:
        body:
          application/json:
            type: array
            items:
              type: userPost
      500:
        body:
          type: string
      400:
        body:
          type: string

/recentposts:
  post:
    description: Returns an array of recently added user posts.
    body:
      application/json:
        example: { "date": "2021-11-07T13:57:49.280+00:00" }
    responses:
      200:
        body:
          application/json:
            type: array
            items:
              type: userPost
      500:
        body:
          type: string

/image:
  post:
    description: "Creates a image in an S3 bucket and returns the object key."
    responses:
      201:
        body:
          application/json:
            type: string,
            example: |
              {
                "id": "a2590b9eb66f"
              }
      400:
        description: "No image file was provided in the request body."
        body:
          type: string
          example: "No Image Provided"
      500:
        body:
          type: string
  /{id}:
    get: 
      description: "Returns the image with the matching id."
      responses:
        200:
          body:
            type: data
        500:
          body:
            type: string
    delete:
      description: "Delete an image."
      responses:
        200:
        500:
          body:
            type: string


/imageurl/{id}:
    get: 
      description: "Returns the image url with the matching id."
      responses:
        200:
          body:
            application/json:
              type: string,
              example: |
                {
                  "url": "https://google.com"
                }
        500:
          body:
            type: string
