name: E2E Tests

# Get .env variables from our repository's secrets
env:
  NODE_ENV: prod

# Run CI on pull request for the main branches
on:
  schedule:
    # Run daily at noon UTC or 8:00AM Atlantic Standard Time
    - cron:  '0 12 * * *'
  # TODO: Remove this before merging  
  push:
    branches:    
      - 'dbo-64'

jobs:
  E2ETests:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout the repository
        uses: actions/checkout@v2

      # Setup Chrome
      - name: Set up Latest Gogle Chrome
        uses: browser-actions/setup-chrome@latest

      # Setup JDK
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      # Run Karate API Tests
      - name: Run Karate API Tests
        run: |
          cd Automation
          mvn test -Dtest=UiTests -Dkarate.env="prod"
