name: Dev deployment from Github to AWS
on:
  push:
    branches:  
    - dev
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@v2
        
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}  
      - name: Build Images
        run: |
          docker build --build-arg API_KEY=${{ secrets.API_KEY }} --build-arg SERVICE_URL=${{ secrets.SERVICE_URL }} -t ${{ secrets.DOCKER_USERNAME }}/engg4000-client ./application
          docker build -t ${{ secrets.DOCKER_USERNAME }}/engg4000-backend ./Service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/engg4000-nginx ./nginx
      
      - name: List images
        run: docker images

      - name: Push Images to Docker Hub
        run: | 
          docker push ${{ secrets.DOCKER_USERNAME }}/engg4000-client
          docker push ${{ secrets.DOCKER_USERNAME }}/engg4000-backend
          docker push ${{ secrets.DOCKER_USERNAME }}/engg4000-nginx

      - name: Get Timestamp
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Run String Replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'

      - name: Generate Deployment Package
        run: zip -r deploy.zip * -x "**node_modules**"

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Nota
          environment_name: Nota-env
          version_label: "Nota-${{ steps.format-time.outputs.replaced }}"
          region: us-east-1
          deployment_package: deploy.zip
      
      - name: Slack Notification
        uses: someimportantcompany/github-actions-slack-message@v1
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
          text: 'Successfully Deployed prod-app-${{ steps.format-time.outputs.replaced }}'
          image-url: https://senior-design-img-bucket.s3.amazonaws.com/elmo.gif
          color: good


